version: '2.3'

services:
  dev:
    container_name: abd-dev
    build:
      context: ./
      dockerfile: docker/dev/dockerfile
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/env.env"
    volumes:
      - ${PWD}:/workspace
      - dataset:/dataset
      - mldisk2:/mldisk2
      - mlsun:/mlsun
    ports:
      - "11000:8000"
      - "11022:22"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul
  mmaction2:
    container_name: abd-mmaction2
    build:
      context: ./
      dockerfile: docker/mmaction2/dockerfile
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/env.env"
    volumes:
      - ${PWD}:/workspace
      - dataset:/dataset
      - mldisk2:/mldisk2
      - mlsun:/mlsun
    ports:
      - "12000:8000"
      - "12022:22"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul
  yolov8:
    container_name: abd-yolov8
    build:
      context: ./
      dockerfile: docker/yolo/yolov8/dockerfile
    env_file:
      - "docker/env.env"
    runtime: nvidia
    restart: always
    ipc: "host"
    volumes:
      - ${PWD}:/workspace
      - dataset:/dataset
      - mldisk2:/mldisk2
      - mlsun:/mlsun
    stdin_open: true
    tty: true
  yolor:
    container_name: abd-yolor
    build:
      context: ./
      dockerfile: docker/yolo/yolor/dockerfile
    env_file:
      - "docker/env.env"
    runtime: nvidia
    restart: always
    ipc: "host"
    volumes:
      - ${PWD}:/workspace
      - dataset:/dataset
      - mldisk2:/mldisk2
      - mlsun:/mlsun
    stdin_open: true
    tty: true
  alphapose:
    container_name: abd-alphapose
    build:
      context: ./
      dockerfile: docker/pose/alphapose/dockerfile
    env_file:
      - "docker/env.env"
    runtime: nvidia
    restart: always
    ipc: "host"
    volumes:
      - ${PWD}:/workspace
      - dataset:/dataset
      - mldisk2:/mldisk2
      - mlsun:/mlsun
    stdin_open: true
    tty: true

volumes:
  dataset:
    driver: local
    driver_opts:
      type: none
      device: /DATA/abd
      o: bind
  mldisk2:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk2.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared/abd"
  mlsun:
    driver_opts:
      type: "nfs"
      o: "addr=mlsun.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"