version: '2.3'

services:
  dev:
    container_name: abd-dev
    build:
      context: ./
      dockerfile: docker/dev/dockerfile
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/dev/env.env"
    volumes:
      - ${PWD}:/workspace
      - dataset:/dataset
    ports:
      - "11000:8000"
      - "11022:22"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul
  mmaction2:
    container_name: abd-mmaction2
    build:
      context: ./
      dockerfile: docker/mmaction2/dockerfile
    runtime: nvidia
    restart: always
    ipc: "host"
    env_file:
      - "docker/mmaction2/env.env"
    volumes:
      - ${PWD}/lib/mmaction2:/workspace
      - dataset:/dataset
    ports:
      - "12000:8000"
      - "12022:22"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Seoul
  yolov8:
    container_name: abd-yolov8
    build:
      context: ./
      dockerfile: docker/yolo/yolov8/dockerfile
    env_file:
      - "docker/yolo/yolov8/env.env"
    runtime: nvidia
    restart: always
    ipc: "host"
    volumes:
      - ${PWD}/lib/yolo/yolov8:/workspace
      - dataset:/dataset
    stdin_open: true
    tty: true
  yolor:
    container_name: abd-yolor
    build:
      context: ./
      dockerfile: docker/yolo/yolor/dockerfile
    env_file:
      - "docker/yolo/yolor/env.env"
    runtime: nvidia
    restart: always
    ipc: "host"
    volumes:
      - ${PWD}/lib/yolo/yolov7:/yolov7
      - ${PWD}/lib/yolo/yolov9:/yolov9
      - dataset:/dataset
    stdin_open: true
    tty: true
  alphapose:
    container_name: abd-alphapose
    build:
      context: ./
      dockerfile: docker/pose/alphapose/dockerfile
    env_file:
      - "docker/pose/alphapose/env.env"
    runtime: nvidia
    restart: always
    ipc: "host"
    volumes:
      - ${PWD}/lib/pose/alphapose:/workspace
      - dataset:/dataset
    stdin_open: true
    tty: true

volumes:
  dataset:
    driver: local
    driver_opts:
      type: none
      device: /DATA