FROM sogangmm/worker-engine:cuda11.6

RUN apt-get update && apt-get -y install \
    python3 python3-pip python3-dev \
    mysql-client libmysqlclient-dev python3-mysqldb \
    libgl1 \
    tzdata git wget ssh vim

WORKDIR /workspace

RUN mv /root/alphapose/* /workspace/alphapose

#RUN pip3 install -r docker/main/requirements.txt