FROM sogangmm/worker-engine:cuda11.6

RUN apt-get update && apt-get -y install \
    python3 python3-pip python3-dev \
    mysql-client libmysqlclient-dev python3-mysqldb \
    libgl1 \
    tzdata git wget ssh vim

RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN echo "root:password" | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes #prohibit-password/' /etc/ssh/sshd_config

RUN pip3 install --upgrade pip
RUN pip3 install setuptools

WORKDIR /workspace
RUN mv /root/alphapose/* /workspace/alphapose
